using dadri_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dadri_api.Configurations.Entities
{
    public class UserProjectConfiguration : IEntityTypeConfiguration<UserProject>
    {
        public void Configure(EntityTypeBuilder<UserProject> builder)
        {
            builder.HasData(
                new UserProject { ProjectId = 1000, ProjectDescription = "Corporate Centre", ProjectCode = "1000", TypeId = 1 },
                new UserProject { ProjectId = 1001, ProjectDescription = "EOC Noida Office", ProjectCode= "1001", TypeId = 1 },
                new UserProject { ProjectId = 1002, ProjectDescription = "Consultancy Wing", ProjectCode= "1002", TypeId = 1 },
                new UserProject { ProjectId = 1003, ProjectDescription = "Northern Region  HeadQuaters", ProjectCode= "1003", TypeId = 1 },
                new UserProject { ProjectId = 1004, ProjectDescription = "Singrauli Super Thermal Power", ProjectCode= "1004", TypeId = 1 },
                new UserProject { ProjectId = 1005, ProjectDescription = "Rihand Super Thermal Power", ProjectCode= "1005", TypeId = 1 },
                new UserProject { ProjectId = 1006, ProjectDescription = "Feroz Gandhi Unchahar  Thermal", ProjectCode= "1006", TypeId = 1 },
                new UserProject { ProjectId = 1007, ProjectDescription = "Tanda Thermal Power Project", ProjectCode= "1007", TypeId = 1 },
                new UserProject { ProjectId = 1008, ProjectDescription = "DBF Head Quarters", ProjectCode= "1008", TypeId = 1 },
                new UserProject { ProjectId = 1010, ProjectDescription = "Badarpur Thermal Power Station", ProjectCode= "1010", TypeId = 1 },
                new UserProject { ProjectId = 1011, ProjectDescription = "National Capital Power Project", ProjectCode= "1011", TypeId = 1 },
                new UserProject { ProjectId = 1012, ProjectDescription = "Auraiya Gas Power Station", ProjectCode= "1012", TypeId = 1 },
                new UserProject { ProjectId = 1013, ProjectDescription = "Anta Gas Power Station", ProjectCode= "1013", TypeId = 1 },
                new UserProject { ProjectId = 1014, ProjectDescription = "National Capital Power Project", ProjectCode= "1014", TypeId = 1 },
                new UserProject { ProjectId = 1015, ProjectDescription = "Faridabad Gas Power Station", ProjectCode= "1015", TypeId = 1 },
                new UserProject { ProjectId = 1016, ProjectDescription = "Western Region HeadQuarters", ProjectCode= "1016", TypeId = 1 },
                new UserProject { ProjectId = 1017, ProjectDescription = "Korba Super Thermal Power", ProjectCode= "1017", TypeId = 1 },
                new UserProject { ProjectId = 1018, ProjectDescription = "Vindhyachal Super Thermal Power", ProjectCode= "1018", TypeId = 1 },
                new UserProject { ProjectId = 1019, ProjectDescription = "Sipat Super Thermal Power", ProjectCode= "1019", TypeId = 1 },
                new UserProject { ProjectId = 1020, ProjectDescription = "Kawas Gas Power Project", ProjectCode= "1020", TypeId = 1 },
                new UserProject { ProjectId = 1021, ProjectDescription = "JHANOR GANDHAR GAS  POWER PROJECT", ProjectCode= "1021", TypeId = 1 },
                new UserProject { ProjectId = 1022, ProjectDescription = "Eastern Region HeadQuarters", ProjectCode= "1022", TypeId = 1 },
                new UserProject { ProjectId = 1023, ProjectDescription = "T&CC Office Kolkata", ProjectCode= "1023", TypeId = 1 },
                new UserProject { ProjectId = 1024, ProjectDescription = "Farakka Super Thermal Power", ProjectCode= "1024", TypeId = 1 },
                new UserProject { ProjectId = 1025, ProjectDescription = "Kahalgaon Super Thermal Power", ProjectCode= "1025", TypeId = 1 },
                new UserProject { ProjectId = 1026, ProjectDescription = "Talcher Super Thermal Power", ProjectCode= "1026", TypeId = 1 },
                new UserProject { ProjectId = 1027, ProjectDescription = "Talcher Thermal Power Station", ProjectCode= "1027", TypeId = 1 },
                new UserProject { ProjectId = 1028, ProjectDescription = "Barh Super Thermal Power", ProjectCode= "1028", TypeId = 1 },
                new UserProject { ProjectId = 1029, ProjectDescription = "North Karanpura Super Thermal", ProjectCode= "1029", TypeId = 1 },
                new UserProject { ProjectId = 1030, ProjectDescription = "Lalmatia Project", ProjectCode= "1030", TypeId = 1 },
                new UserProject { ProjectId = 1031, ProjectDescription = "SOUTHERN REGION HEAD QUARTERS", ProjectCode= "1031", TypeId = 1 },
                new UserProject { ProjectId = 1032, ProjectDescription = "T&CC Office Chennai", ProjectCode= "1032", TypeId = 1 },
                new UserProject { ProjectId = 1033, ProjectDescription = "Ramagundam Super Thermal Power", ProjectCode= "1033", TypeId = 1 },
                new UserProject { ProjectId = 1034, ProjectDescription = "Rajiv Gandhi Combined Cycle", ProjectCode= "1034", TypeId = 1 },
                new UserProject { ProjectId = 1035, ProjectDescription = "Simhadri Super Thermal Power", ProjectCode= "1035", TypeId = 1 },
                new UserProject { ProjectId = 1036, ProjectDescription = "Mangalore Super Thermal Power Project", ProjectCode= "1036", TypeId = 1 },
                new UserProject { ProjectId = 1037, ProjectDescription = "KOLDAM HYDRO POWER PROJECT", ProjectCode= "1037", TypeId = 1 },
                new UserProject { ProjectId = 1038, ProjectDescription = "TVHPP", ProjectCode= "1038", TypeId = 1 },
                new UserProject { ProjectId = 1039, ProjectDescription = "Lahorinag - Pala Hydro Power", ProjectCode= "1039", TypeId = 1 },
                new UserProject { ProjectId = 1040, ProjectDescription = "Pakri Barwadih,Chat Bariatu &", ProjectCode= "1040", TypeId = 1 },
                new UserProject { ProjectId = 1041, ProjectDescription = "WRHQ II", ProjectCode= "1041", TypeId = 1 },
                new UserProject { ProjectId = 1042, ProjectDescription = "Bongaigaon Thermal Power Project", ProjectCode= "1042", TypeId = 1 },
                new UserProject { ProjectId = 1043, ProjectDescription = "Mouda Super Thermal Power", ProjectCode= "1043", TypeId = 1 },
                new UserProject { ProjectId = 1044, ProjectDescription = "ERHQ II", ProjectCode= "1044", TypeId = 1 },
                new UserProject { ProjectId = 1045, ProjectDescription = "Solapur STPP", ProjectCode= "1045", TypeId = 1 },
                new UserProject { ProjectId = 1046, ProjectDescription = "Kudgi Super Thermal Power Project", ProjectCode= "1046", TypeId = 1 },
                new UserProject { ProjectId = 1047, ProjectDescription = "LARA SUPER THERMAL POWER PROJECT", ProjectCode= "1047", TypeId = 1 },
                new UserProject { ProjectId = 1048, ProjectDescription = "A&N Islands SOLAR PV", ProjectCode= "1048", TypeId = 1 },
                new UserProject { ProjectId = 1049, ProjectDescription = "Gadarwara STPP", ProjectCode= "1049", TypeId = 1 },
                new UserProject { ProjectId = 1050, ProjectDescription = "Rajgarh SOLAR PV", ProjectCode= "1050", TypeId = 1 },
                new UserProject { ProjectId = 1051, ProjectDescription = "Rammam Hydro Power Project.", ProjectCode= "1051", TypeId = 1 },
                new UserProject { ProjectId = 1052, ProjectDescription = "Lata Tapovan Hydro Power Project", ProjectCode= "1052", TypeId = 1 },
                new UserProject { ProjectId = 1053, ProjectDescription = "Darlipali STPP", ProjectCode= "1053", TypeId = 1 },
                new UserProject { ProjectId = 1054, ProjectDescription = "KHARGONE STPP", ProjectCode= "1054", TypeId = 1 },
                new UserProject { ProjectId = 1055, ProjectDescription = "Ananthapuramu UM Solar PP", ProjectCode= "1055", TypeId = 1 },
                new UserProject { ProjectId = 1056, ProjectDescription = "HRHQ", ProjectCode= "1056", TypeId = 1 },
                new UserProject { ProjectId = 1057, ProjectDescription = "TELANGANA Super Thermal Power", ProjectCode= "1057", TypeId = 1 },
                new UserProject { ProjectId = 1058, ProjectDescription = "Bhadla Solar PV (4 X 65 MW)", ProjectCode= "1058", TypeId = 1 },
                new UserProject { ProjectId = 1059, ProjectDescription = "Mandsaur Solar PV (5X50 MW)", ProjectCode= "1059", TypeId = 1 },
                new UserProject { ProjectId = 1060, ProjectDescription = "Rajmol Wind energy 50 MW", ProjectCode= "1060", TypeId = 1 },
                new UserProject { ProjectId = 1061, ProjectDescription = "OE Block - KG-OSN-2009/1", ProjectCode= "1061", TypeId = 1 },
                new UserProject { ProjectId = 1062, ProjectDescription = "OE Block - KG-OSN-2009/4", ProjectCode= "1062", TypeId = 1 },
                new UserProject { ProjectId = 1063, ProjectDescription = "OE Block - KG-OSN-2009/13", ProjectCode= "1063", TypeId = 1 },
                new UserProject { ProjectId = 1064, ProjectDescription = "OE Block - CB-ONN-2009/5", ProjectCode= "1064", TypeId = 1 },
                new UserProject { ProjectId = 1070, ProjectDescription = "Dulanga Coal Mining Project", ProjectCode= "1070", TypeId = 1 },
                new UserProject { ProjectId = 1071, ProjectDescription = "Talaipalli Coal Mining Project", ProjectCode= "1071", TypeId = 1 },
                new UserProject { ProjectId = 1072, ProjectDescription = "Barauni  Thermal Power Plant", ProjectCode= "1072", TypeId = 1 },
                new UserProject { ProjectId = 1073, ProjectDescription = "Bilhaur Solar PV Plant", ProjectCode= "1073", TypeId = 1 },
                new UserProject { ProjectId = 1074, ProjectDescription = "Coal Mining HeadQuarters", ProjectCode= "1074", TypeId = 1 },
                new UserProject { ProjectId = 1075, ProjectDescription = "Jetsar SOLAR PV", ProjectCode= "1075", TypeId = 1 },
                new UserProject { ProjectId = 1076, ProjectDescription = "Devikot  SOLAR PV", ProjectCode= "1076", TypeId = 1 },
                new UserProject { ProjectId = 1077, ProjectDescription = "Sambhu Ki Bhurj – I Solar Project", ProjectCode= "1077", TypeId = 1 },
                new UserProject { ProjectId = 1078, ProjectDescription = "Kerandari  'A' CMP", ProjectCode= "1078", TypeId = 1 },
                new UserProject { ProjectId = 1079, ProjectDescription = "Chatti-Bariatu Coal Mining Project", ProjectCode= "1079", TypeId = 1 },
                new UserProject { ProjectId = 1080, ProjectDescription = "Fatehgarh Solar PV Proj-296MW", ProjectCode= "1080", TypeId = 1 },
                new UserProject { ProjectId = 1081, ProjectDescription = "Nokhra Solar PV Project -300MW", ProjectCode= "1081", TypeId = 1 },
                new UserProject { ProjectId = 1082, ProjectDescription = "Sambhu Ki Bhurj – II Solar Project", ProjectCode= "1082", TypeId = 1 },
                new UserProject { ProjectId = 1083, ProjectDescription = "Ettayapuram SolarPVP-230 MW", ProjectCode= "1083", TypeId = 1 },
                new UserProject { ProjectId = 2590, ProjectDescription = "NTPC --CHANDIGARH Comm. Office", ProjectCode= "1A01", TypeId = 1 },
                new UserProject { ProjectId = 2591, ProjectDescription = "Rammam Hydro Power Project.", ProjectCode= "1A51", TypeId = 1 },
                new UserProject { ProjectId = 2010, ProjectDescription = "NESCL Corporate Office", ProjectCode= "2010", TypeId = 1 },
                new UserProject { ProjectId = 2015, ProjectDescription = "Nabinagar Thermal Power Project", ProjectCode= "2015", TypeId = 1 },
                new UserProject { ProjectId = 2020, ProjectDescription = "NVVN - Corporate Office", ProjectCode= "2020", TypeId = 1 },
                new UserProject { ProjectId = 2025, ProjectDescription = "Patratu Vidyut Utpadan Nigam Ltd", ProjectCode= "2025", TypeId = 1 },
                new UserProject { ProjectId = 2030, ProjectDescription = "NHL  Corporate Office", ProjectCode= "2030", TypeId = 1 },
                new UserProject { ProjectId = 2031, ProjectDescription = "Rammam Hydel Project III", ProjectCode= "2031", TypeId = 1 },
                new UserProject { ProjectId = 2032, ProjectDescription = "Lata Tapovan Hydro Power Project", ProjectCode= "2032", TypeId = 1 },
                new UserProject { ProjectId = 2035, ProjectDescription = "Nabinagar Power Generating Company", ProjectCode= "2035", TypeId = 1 },
                new UserProject { ProjectId = 2040, ProjectDescription = "Muzaffarpur Thermal Power Station", ProjectCode= "2040", TypeId = 1 },
                new UserProject { ProjectId = 2045, ProjectDescription = "NTPC Mining limited", ProjectCode= "2045", TypeId = 1 },
                new UserProject { ProjectId = 2060, ProjectDescription = "NTPC Renewable Energy Limited", ProjectCode= "2060", TypeId = 1 },
                new UserProject { ProjectId = 2065, ProjectDescription = "NEWS", ProjectCode= "2065", TypeId = 1 },
                new UserProject { ProjectId = 2200, ProjectDescription = "NVVNL Simhadri", ProjectCode= "2200", TypeId = 1 },
                new UserProject { ProjectId = 2201, ProjectDescription = "NVVNL RSTPP", ProjectCode= "2201", TypeId = 1 },
                new UserProject { ProjectId = 2203, ProjectDescription = "NVVNL NCTPP", ProjectCode= "2203", TypeId = 1 },
                new UserProject { ProjectId = 2204, ProjectDescription = "NVVNL SSTPP", ProjectCode= "2204", TypeId = 1 },
                new UserProject { ProjectId = 2205, ProjectDescription = "NVVNL Rihand", ProjectCode= "2205", TypeId = 1 },
                new UserProject { ProjectId = 2206, ProjectDescription = "NVVNL Badarpur", ProjectCode= "2206", TypeId = 1 },
                new UserProject { ProjectId = 2207, ProjectDescription = "NVVNL Unchahar", ProjectCode= "2207", TypeId = 1 },
                new UserProject { ProjectId = 2208, ProjectDescription = "NVVNL Tanda", ProjectCode= "2208", TypeId = 1 },
                new UserProject { ProjectId = 2209, ProjectDescription = "NVVNL Vindhyachal", ProjectCode= "2209", TypeId = 1 },
                new UserProject { ProjectId = 2210, ProjectDescription = "NVVNL Korba", ProjectCode= "2210", TypeId = 1 },
                new UserProject { ProjectId = 2211, ProjectDescription = "NVVNL Sipat", ProjectCode= "2211", TypeId = 1 },
                new UserProject { ProjectId = 2212, ProjectDescription = "NVVNL Kahalgaon", ProjectCode= "2212", TypeId = 1 },
                new UserProject { ProjectId = 2213, ProjectDescription = "NVVNL Farakka", ProjectCode= "2213", TypeId = 1 },
                new UserProject { ProjectId = 2214, ProjectDescription = "NVVNL Talcher (Kaniha)", ProjectCode= "2214", TypeId = 1 },
                new UserProject { ProjectId = 2215, ProjectDescription = "NVVNL Talcher Thermal", ProjectCode= "2215", TypeId = 1 },
                new UserProject { ProjectId = 2216, ProjectDescription = "NVVNL Barh", ProjectCode= "2216", TypeId = 1 },
                new UserProject { ProjectId = 2217, ProjectDescription = "NVVNL New BongaiGaon", ProjectCode= "2217", TypeId = 1 },
                new UserProject { ProjectId = 2601, ProjectDescription = "Chhatargarh Solar PV Project", ProjectCode= "2601", TypeId = 1 },
                new UserProject { ProjectId = 2602, ProjectDescription = "Bhainsara Solar PV Project", ProjectCode= "2602", TypeId = 1 },
                new UserProject { ProjectId = 2603, ProjectDescription = "Amreshwar Solar PV Project", ProjectCode= "2603", TypeId = 1 },
                new UserProject { ProjectId = 7120, ProjectDescription = "NBPPL", ProjectCode= "7120", TypeId = 1 },
                new UserProject { ProjectId = 7130, ProjectDescription = "TELK", ProjectCode= "7130", TypeId = 1 },
                new UserProject { ProjectId = 7140, ProjectDescription = "NPEX", ProjectCode= "7140", TypeId = 1 },
                new UserProject { ProjectId = 7150, ProjectDescription = "BFNSL", ProjectCode= "7150", TypeId = 1 },
                new UserProject { ProjectId = 7160, ProjectDescription = "EESL", ProjectCode= "7160", TypeId = 1 },
                new UserProject { ProjectId = 7180, ProjectDescription = "Adra-JV", ProjectCode= "7180", TypeId = 1 },
                new UserProject { ProjectId = 7190, ProjectDescription = "CIL-NTPC", ProjectCode= "7190", TypeId = 1 },
                new UserProject { ProjectId = 7210, ProjectDescription = "PARPL", ProjectCode= "7210", TypeId = 1 },
                new UserProject { ProjectId = 7230, ProjectDescription = "NTPC EDMC Waste Solutions Priv", ProjectCode= "7230", TypeId = 1 },
                new UserProject { ProjectId = 7300, ProjectDescription = "TPCL", ProjectCode= "7300", TypeId = 1 },
                new UserProject { ProjectId = 7301, ProjectDescription = "BIFPC", ProjectCode= "7301", TypeId = 1 },
                new UserProject { ProjectId = 7500, ProjectDescription = "HURL-HQs", ProjectCode= "7500", TypeId = 1 },
                new UserProject { ProjectId = 5010, ProjectDescription = "NHL", ProjectCode= "5010", TypeId = 1 },
                new UserProject { ProjectId = 5030, ProjectDescription = "NVVN", ProjectCode= "5030", TypeId = 1 },
                new UserProject { ProjectId = 5040, ProjectDescription = "NTPC Renewable Energy Limited", ProjectCode= "5040", TypeId = 1 },
                new UserProject { ProjectId = 5050, ProjectDescription = "NESCL", ProjectCode= "5050", TypeId = 1 },
                new UserProject { ProjectId = 5060, ProjectDescription = "NTPC Foundation", ProjectCode= "5060", TypeId = 1 },
                new UserProject { ProjectId = 5070, ProjectDescription = "PPDC", ProjectCode= "5070", TypeId = 1 },
                new UserProject { ProjectId = 5080, ProjectDescription = "BRBCL", ProjectCode= "5080", TypeId = 1 },
                new UserProject { ProjectId = 7070, ProjectDescription = "Kanti", ProjectCode= "7070", TypeId = 1 },
                new UserProject { ProjectId = 7110, ProjectDescription = "NPGCL", ProjectCode= "7110", TypeId = 1 },
                new UserProject { ProjectId = 7170, ProjectDescription = "Patratu", ProjectCode= "7170", TypeId = 1 },
                new UserProject { ProjectId = 404, ProjectDescription = "Talcher Kaniha", ProjectCode= "404", TypeId = 1 },
                new UserProject { ProjectId = 405, ProjectDescription = "Talcher Thermal", ProjectCode= "405", TypeId = 1 },
                new UserProject { ProjectId = 408, ProjectDescription = "Bongaigaon", ProjectCode= "408", TypeId = 1 },
                new UserProject { ProjectId = 410, ProjectDescription = "ER2- HQs", ProjectCode= "410", TypeId = 1 },
                new UserProject { ProjectId = 411, ProjectDescription = "Darlipalli", ProjectCode= "411", TypeId = 1 },
                new UserProject { ProjectId = 412, ProjectDescription = "Gajamara", ProjectCode= "412", TypeId = 1 },
                new UserProject { ProjectId = 431, ProjectDescription = "SSC-ER-2", ProjectCode= "431", TypeId = 1 },
                new UserProject { ProjectId = 502, ProjectDescription = "Korba", ProjectCode= "502", TypeId = 1 },
                new UserProject { ProjectId = 506, ProjectDescription = "Sipat", ProjectCode= "506", TypeId = 1 },
                new UserProject { ProjectId = 510, ProjectDescription = "Lara", ProjectCode= "510", TypeId = 1 },
                new UserProject { ProjectId = 511, ProjectDescription = "Khargone", ProjectCode= "511", TypeId = 1 },
                new UserProject { ProjectId = 512, ProjectDescription = "Gadarwara", ProjectCode= "512", TypeId = 1 },
                new UserProject { ProjectId = 513, ProjectDescription = "Barethi", ProjectCode= "513", TypeId = 1 },
                new UserProject { ProjectId = 515, ProjectDescription = "Mandsaur Solar", ProjectCode= "515", TypeId = 1 },
                new UserProject { ProjectId = 550, ProjectDescription = "WR2- HQs", ProjectCode= "550", TypeId = 1 },
                new UserProject { ProjectId = 551, ProjectDescription = "SSC-WR-2", ProjectCode= "551", TypeId = 1 },
                new UserProject { ProjectId = 3002, ProjectDescription = "Rajgarh Solar", ProjectCode= "3002", TypeId = 1 },
                new UserProject { ProjectId = 3000, ProjectDescription = "RE & N- HQs", ProjectCode= "3000", TypeId = 1 },
                new UserProject { ProjectId = 310, ProjectDescription = "DBF- HQs", ProjectCode= "310", TypeId = 1 }
                );
        }
    }
}
