using dadri_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dadri_api.Configurations.Entities
{
    public class UserGradeConfiguration : IEntityTypeConfiguration<UserGrade>
    {
        public void Configure(EntityTypeBuilder<UserGrade> builder)
        {
            builder.HasIndex(p => new { p.GradeCode }).IsUnique(true);
            builder.HasData(new UserGrade { GradeId = 1, GradeDescription = "W0", GradeCode = "1", TypeId = 1 },
            new UserGrade { GradeId = 2, GradeDescription = "W0", GradeCode = "2", TypeId = 1 },
            new UserGrade { GradeId = 3, GradeDescription = "W0", GradeCode = "3", TypeId = 1 },
            new UserGrade { GradeId = 4, GradeDescription = "W1S   W1EG", GradeCode = "4", TypeId = 1 },
            new UserGrade { GradeId = 5, GradeDescription = "W1SS  w1EGEG", GradeCode = "5", TypeId = 1 },
            new UserGrade { GradeId = 6, GradeDescription = "W1", GradeCode = "6", TypeId = 1 },
            new UserGrade { GradeId = 7, GradeDescription = "W2S   W2EG", GradeCode = "7", TypeId = 1 },
            new UserGrade { GradeId = 8, GradeDescription = "W2SS  W3EG", GradeCode = "8", TypeId = 1 },
            new UserGrade { GradeId = 9, GradeDescription = "W2", GradeCode = "9", TypeId = 1 },
            new UserGrade { GradeId = 10, GradeDescription = "W3S   W3EG", GradeCode = "10", TypeId = 1 },
            new UserGrade { GradeId = 11, GradeDescription = "W3SS  W4EG", GradeCode = "11", TypeId = 1 },
            new UserGrade { GradeId = 12, GradeDescription = "W3", GradeCode = "12", TypeId = 1 },
            new UserGrade { GradeId = 13, GradeDescription = "W4S   W4EG", GradeCode = "13", TypeId = 1 },
            new UserGrade { GradeId = 14, GradeDescription = "W4SS  W4EGEG", GradeCode = "14", TypeId = 1 },
            new UserGrade { GradeId = 15, GradeDescription = "W4", GradeCode = "15", TypeId = 1 },
            new UserGrade { GradeId = 16, GradeDescription = "W5S   W5EG", GradeCode = "16", TypeId = 1 },
            new UserGrade { GradeId = 17, GradeDescription = "W5SS  W5EGEG", GradeCode = "17", TypeId = 1 },
            new UserGrade { GradeId = 18, GradeDescription = "W5", GradeCode = "18", TypeId = 1 },
            new UserGrade { GradeId = 19, GradeDescription = "W6S   W6EG", GradeCode = "19", TypeId = 1 },
            new UserGrade { GradeId = 20, GradeDescription = "W6SS  W6EGEG", GradeCode = "20", TypeId = 1 },
            new UserGrade { GradeId = 21, GradeDescription = "W6", GradeCode = "21", TypeId = 1 },
            new UserGrade { GradeId = 22, GradeDescription = "W7S   W7EG", GradeCode = "22", TypeId = 1 },
            new UserGrade { GradeId = 23, GradeDescription = "W7SS  W8EG", GradeCode = "23", TypeId = 1 },
            new UserGrade { GradeId = 24, GradeDescription = "W7", GradeCode = "24", TypeId = 1 },
            new UserGrade { GradeId = 25, GradeDescription = "W8S   W8EG", GradeCode = "25", TypeId = 1 },
            new UserGrade { GradeId = 26, GradeDescription = "W8SS  W9EG", GradeCode = "26", TypeId = 1 },
            new UserGrade { GradeId = 27, GradeDescription = "W8", GradeCode = "27", TypeId = 1 },
            new UserGrade { GradeId = 28, GradeDescription = "W9S   W9EG", GradeCode = "28", TypeId = 1 },
            new UserGrade { GradeId = 29, GradeDescription = "W9SS  W9EGEG", GradeCode = "29", TypeId = 1 },
            new UserGrade { GradeId = 30, GradeDescription = "W9", GradeCode = "30", TypeId = 1 },
            new UserGrade { GradeId = 31, GradeDescription = "W10S  W10EG", GradeCode = "31", TypeId = 1 },
            new UserGrade { GradeId = 32, GradeDescription = "W10SS W10EGEG", GradeCode = "32", TypeId = 1 },
            new UserGrade { GradeId = 33, GradeDescription = "W10", GradeCode = "33", TypeId = 1 },
            new UserGrade { GradeId = 34, GradeDescription = "W11S  W11EG", GradeCode = "34", TypeId = 1 },
            new UserGrade { GradeId = 35, GradeDescription = "W11SS W11EGEG", GradeCode = "35", TypeId = 1 },
            new UserGrade { GradeId = 36, GradeDescription = "W11", GradeCode = "36", TypeId = 1 },
            new UserGrade { GradeId = 37, GradeDescription = "WSG", GradeCode = "37", TypeId = 1 },
            new UserGrade { GradeId = 38, GradeDescription = "WSG", GradeCode = "38", TypeId = 1 },
            new UserGrade { GradeId = 39, GradeDescription = "WSG", GradeCode = "39", TypeId = 1 },
            new UserGrade { GradeId = 40, GradeDescription = "WSG", GradeCode = "40", TypeId = 1 },
            new UserGrade { GradeId = 41, GradeDescription = "S1", GradeCode = "41", TypeId = 1 },
            new UserGrade { GradeId = 42, GradeDescription = "SLPS", GradeCode = "42", TypeId = 1 },
            new UserGrade { GradeId = 43, GradeDescription = "reserve", GradeCode = "43", TypeId = 1 },
            new UserGrade { GradeId = 44, GradeDescription = "S2", GradeCode = "44", TypeId = 1 },
            new UserGrade { GradeId = 45, GradeDescription = "reserve", GradeCode = "45", TypeId = 1 },
            new UserGrade { GradeId = 46, GradeDescription = "reserve", GradeCode = "46", TypeId = 1 },
            new UserGrade { GradeId = 47, GradeDescription = "S3", GradeCode = "47", TypeId = 1 },
            new UserGrade { GradeId = 48, GradeDescription = "reserve", GradeCode = "48", TypeId = 1 },
            new UserGrade { GradeId = 49, GradeDescription = "reserve", GradeCode = "49", TypeId = 1 },
            new UserGrade { GradeId = 50, GradeDescription = "S4", GradeCode = "50", TypeId = 1 },
            new UserGrade { GradeId = 51, GradeDescription = "reserve", GradeCode = "51", TypeId = 1 },
            new UserGrade { GradeId = 52, GradeDescription = "reserve", GradeCode = "52", TypeId = 1 },
            new UserGrade { GradeId = 53, GradeDescription = "SSG", GradeCode = "53", TypeId = 1 },
            new UserGrade { GradeId = 54, GradeDescription = "reserve", GradeCode = "54", TypeId = 1 },
            new UserGrade { GradeId = 55, GradeDescription = "reserve", GradeCode = "55", TypeId = 1 },
            new UserGrade { GradeId = 56, GradeDescription = "SLPS- E1", GradeCode = "56", TypeId = 1 },
            new UserGrade { GradeId = 57, GradeDescription = "SLPS- E2", GradeCode = "57", TypeId = 1 },
            new UserGrade { GradeId = 58, GradeDescription = "SLPS- E3", GradeCode = "58", TypeId = 1 },
            new UserGrade { GradeId = 59, GradeDescription = "E0", GradeCode = "59", TypeId = 1 },
            new UserGrade { GradeId = 60, GradeDescription = "E1", GradeCode = "60", TypeId = 1 },
            new UserGrade { GradeId = 61, GradeDescription = "reserve", GradeCode = "61", TypeId = 1 },
            new UserGrade { GradeId = 62, GradeDescription = "reserve", GradeCode = "62", TypeId = 1 },
            new UserGrade { GradeId = 63, GradeDescription = "E2", GradeCode = "63", TypeId = 1 },
            new UserGrade { GradeId = 64, GradeDescription = "reserve", GradeCode = "64", TypeId = 1 },
            new UserGrade { GradeId = 65, GradeDescription = "reserve", GradeCode = "65", TypeId = 1 },
            new UserGrade { GradeId = 66, GradeDescription = "E2A", GradeCode = "66", TypeId = 1 },
            new UserGrade { GradeId = 67, GradeDescription = "reserve", GradeCode = "67", TypeId = 1 },
            new UserGrade { GradeId = 68, GradeDescription = "reserve", GradeCode = "68", TypeId = 1 },
            new UserGrade { GradeId = 69, GradeDescription = "E3", GradeCode = "69", TypeId = 1 },
            new UserGrade { GradeId = 70, GradeDescription = "reserve", GradeCode = "70", TypeId = 1 },
            new UserGrade { GradeId = 71, GradeDescription = "reserve", GradeCode = "71", TypeId = 1 },
            new UserGrade { GradeId = 72, GradeDescription = "E4", GradeCode = "72", TypeId = 1 },
            new UserGrade { GradeId = 73, GradeDescription = "reserve", GradeCode = "73", TypeId = 1 },
            new UserGrade { GradeId = 74, GradeDescription = "reserve", GradeCode = "74", TypeId = 1 },
            new UserGrade { GradeId = 75, GradeDescription = "E5", GradeCode = "75", TypeId = 1 },
            new UserGrade { GradeId = 76, GradeDescription = "reserve", GradeCode = "76", TypeId = 1 },
            new UserGrade { GradeId = 77, GradeDescription = "reserve", GradeCode = "77", TypeId = 1 },
            new UserGrade { GradeId = 78, GradeDescription = "E6", GradeCode = "78", TypeId = 1 },
            new UserGrade { GradeId = 79, GradeDescription = "reserve", GradeCode = "79", TypeId = 1 },
            new UserGrade { GradeId = 80, GradeDescription = "reserve", GradeCode = "80", TypeId = 1 },
            new UserGrade { GradeId = 81, GradeDescription = "E7", GradeCode = "81", TypeId = 1 },
            new UserGrade { GradeId = 82, GradeDescription = "reserve", GradeCode = "82", TypeId = 1 },
            new UserGrade { GradeId = 83, GradeDescription = "reserve", GradeCode = "83", TypeId = 1 },
            new UserGrade { GradeId = 84, GradeDescription = "E7A", GradeCode = "84", TypeId = 1 },
            new UserGrade { GradeId = 85, GradeDescription = "E7", GradeCode = "85", TypeId = 1 },
            new UserGrade { GradeId = 86, GradeDescription = "reserve", GradeCode = "86", TypeId = 1 },
            new UserGrade { GradeId = 87, GradeDescription = "E8", GradeCode = "87", TypeId = 1 },
            new UserGrade { GradeId = 88, GradeDescription = "E8-1", GradeCode = "88", TypeId = 1 },
            new UserGrade { GradeId = 89, GradeDescription = "E8-2", GradeCode = "89", TypeId = 1 },
            new UserGrade { GradeId = 90, GradeDescription = "E9", GradeCode = "90", TypeId = 1 },
            new UserGrade { GradeId = 91, GradeDescription = "reserve", GradeCode = "91", TypeId = 1 },
            new UserGrade { GradeId = 92, GradeDescription = "reserve", GradeCode = "92", TypeId = 1 },
            new UserGrade { GradeId = 93, GradeDescription = "DIR", GradeCode = "93", TypeId = 1 },
            new UserGrade { GradeId = 94, GradeDescription = "reserve", GradeCode = "94", TypeId = 1 },
            new UserGrade { GradeId = 95, GradeDescription = "reserve", GradeCode = "95", TypeId = 1 },
            new UserGrade { GradeId = 96, GradeDescription = "CMD", GradeCode = "96", TypeId = 1 },
            new UserGrade { GradeId = 97, GradeDescription = "reserve", GradeCode = "97", TypeId = 1 },
            new UserGrade { GradeId = 98, GradeDescription = "reserve", GradeCode = "98", TypeId = 1 },
            new UserGrade { GradeId = 99, GradeDescription = "CISF", GradeCode = "99", TypeId = 1 },
            new UserGrade { GradeId = 100, GradeDescription = "Others", GradeCode = "100", TypeId = 1 }
            );

        }
    }
}
