// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dadri_api.Data;

namespace dadri_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210804001824_addeddefaultroles")]
    partial class addeddefaultroles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "181c5a2d-514c-4cf6-8b0f-24bcbfd24403",
                            ConcurrencyStamp = "964db67e-5d5c-4eaa-a1a7-86fd5b30eafd",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "8490a035-9b6c-400d-8a26-38714b9f889c",
                            ConcurrencyStamp = "b98f4360-f58e-4464-a0e6-18dfa8478844",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "eb8c7299-9ff5-418d-91fc-d86df9b6cfab",
                            ConcurrencyStamp = "779202a9-e0c7-4637-941b-dd589b7f2e6b",
                            Name = "Sas",
                            NormalizedName = "SAS"
                        },
                        new
                        {
                            Id = "d5634682-059f-44d1-8ba7-808da33e1bca",
                            ConcurrencyStamp = "2f62299c-1b44-4905-968d-50ed90a27d4d",
                            Name = "SasAdmin",
                            NormalizedName = "SASADMIN"
                        },
                        new
                        {
                            Id = "0f84f316-f393-48fb-b99a-33c02a04bc24",
                            ConcurrencyStamp = "385ddb28-be2a-4153-9da9-b75c69d4f6c7",
                            Name = "Welfare",
                            NormalizedName = "WELFARE"
                        },
                        new
                        {
                            Id = "0a692dd4-702f-42e0-96e8-464822e7f224",
                            ConcurrencyStamp = "d2c3f4e0-c004-4939-9dfb-834c942514e4",
                            Name = "WelfareNtpcClub",
                            NormalizedName = "WELFARENTPCCLUB"
                        },
                        new
                        {
                            Id = "3ed1fca2-ea3c-44e4-a952-18f0d5bc70af",
                            ConcurrencyStamp = "c1270c01-48b1-45e5-a618-22940d2cf545",
                            Name = "WelfareNtpcClubAdmin",
                            NormalizedName = "WELFARENTPCCLUBADMIN"
                        },
                        new
                        {
                            Id = "0a523944-ab6f-4636-88bf-5cf927a13843",
                            ConcurrencyStamp = "98c16781-89f7-4ed7-8dfa-4c44d6017d0e",
                            Name = "WelfareVrc",
                            NormalizedName = "WELFAREVRC"
                        },
                        new
                        {
                            Id = "4536acd7-efd1-475f-963c-837268b0d3f7",
                            ConcurrencyStamp = "10aaba34-2797-4663-9588-8d4b1888e952",
                            Name = "WelfareVrcAdmin",
                            NormalizedName = "WELFAREVRCADMIN"
                        },
                        new
                        {
                            Id = "9a9fa3c8-274d-483e-ae66-7968a783bf28",
                            ConcurrencyStamp = "d97990e7-2dd9-4cbb-922c-6e0065910851",
                            Name = "Bus",
                            NormalizedName = "BUS"
                        },
                        new
                        {
                            Id = "93591552-28d0-4b96-be38-a38023e91dd1",
                            ConcurrencyStamp = "6049ad68-17b7-40ce-9375-61a8a2deff3e",
                            Name = "BusConductor",
                            NormalizedName = "BUSCONDUCTOR"
                        },
                        new
                        {
                            Id = "e4791609-aa87-4cfd-9391-d36f5a3b14ce",
                            ConcurrencyStamp = "17f5277a-10de-4284-9668-80318d46f0c9",
                            Name = "BusWallet",
                            NormalizedName = "BUSWALLET"
                        },
                        new
                        {
                            Id = "7e5ceeb8-262a-4250-8075-e233ce1ac71d",
                            ConcurrencyStamp = "8db7e235-6a39-435f-b4a8-825c8151115c",
                            Name = "BusWalletAdmin",
                            NormalizedName = "BUSWALLETADMIN"
                        },
                        new
                        {
                            Id = "3114da27-d4a6-45e0-b873-28d5cc984c0d",
                            ConcurrencyStamp = "7723cb33-fb8a-4e1c-91b4-a878741b2ff0",
                            Name = "HospitalAdmin",
                            NormalizedName = "HOSPITALADMIN"
                        },
                        new
                        {
                            Id = "3cfb23ae-3cb6-4f11-8ede-75aa2708c630",
                            ConcurrencyStamp = "adae60c4-acba-4cf5-88df-24c60e837a92",
                            Name = "Movie",
                            NormalizedName = "MOVIE"
                        },
                        new
                        {
                            Id = "5f0bd33a-b95d-4610-87e4-5a7151e90e3c",
                            ConcurrencyStamp = "27230a3b-254f-43be-87d5-f57110cd347a",
                            Name = "MovieAdmin",
                            NormalizedName = "MOVIEADMIN"
                        },
                        new
                        {
                            Id = "3ed16947-a1b3-4c0a-ae2c-446a0de1e767",
                            ConcurrencyStamp = "61e4a40d-0517-4872-b6f2-d28fce7518e0",
                            Name = "Dsm",
                            NormalizedName = "DSM"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("dadri_api.Data.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("dadri_api.Data.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Jamaica",
                            ShortName = "JM"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Bahamas",
                            ShortName = "BS"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Cayman Island",
                            ShortName = "CI"
                        });
                });

            modelBuilder.Entity("dadri_api.Data.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("HotelId");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Address = "America",
                            CountryId = 1,
                            Name = "America Resort and Spa",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            HotelId = 2,
                            Address = "Negril",
                            CountryId = 3,
                            Name = "Sandels Resort and Spa",
                            Rating = 3.5
                        },
                        new
                        {
                            HotelId = 3,
                            Address = "Nassual",
                            CountryId = 3,
                            Name = "Grand Palldium",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("dadri_api.Data.TownshipQuarter", b =>
                {
                    b.Property<int>("QuarterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Isoccupied")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccupiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuarterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuarterDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QuarterId");

                    b.ToTable("TownshipQuarters");
                });

            modelBuilder.Entity("dadri_api.Data.TownshipQuarterArchive", b =>
                {
                    b.Property<int>("QuarterAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Isoccupied")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccupiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuarterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuarterDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuarterId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VacatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QuarterAId");

                    b.ToTable("TownshipQuarterArchives");
                });

            modelBuilder.Entity("dadri_api.Data.TypeIndicator", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("TypeIndicators");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            TypeDescription = "LAN Insert"
                        },
                        new
                        {
                            TypeId = 2,
                            TypeDescription = "LAN Update"
                        },
                        new
                        {
                            TypeId = 3,
                            TypeDescription = "LAN Delete"
                        },
                        new
                        {
                            TypeId = 4,
                            TypeDescription = "WAN Insert"
                        },
                        new
                        {
                            TypeId = 5,
                            TypeDescription = "WAN Update"
                        },
                        new
                        {
                            TypeId = 6,
                            TypeDescription = "Do Nothing"
                        });
                });

            modelBuilder.Entity("dadri_api.Data.URole", b =>
                {
                    b.Property<int>("URoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("URoleId");

                    b.ToTable("URoles");

                    b.HasData(
                        new
                        {
                            URoleId = 1,
                            IsDefault = false,
                            RoleDescription = "Registration Approval",
                            TypeId = 1
                        },
                        new
                        {
                            URoleId = 2,
                            IsDefault = true,
                            RoleDescription = "Login",
                            TypeId = 1
                        },
                        new
                        {
                            URoleId = 3,
                            IsDefault = false,
                            RoleDescription = "Login Approval",
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("dadri_api.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryIntoGrade")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("IntercomH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntercomH2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntercomO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntercomO2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mobile2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NTPCJoining")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalAreaId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePathImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProjectJoining")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuarterId")
                        .HasColumnType("int");

                    b.Property<int>("QuarterId2")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistratinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Mobile")
                        .IsUnique()
                        .HasFilter("[Mobile] IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ApprovalDate = new DateTime(2021, 8, 4, 5, 48, 24, 166, DateTimeKind.Local).AddTicks(7515),
                            ApprovedBy = "009392",
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptId = 0,
                            Email = "narendrasingh@ntpc.co.in",
                            EmpNo = "009392",
                            EmployerId = 1,
                            EntryIntoGrade = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Narendra",
                            GradeId = 0,
                            IsActive = true,
                            IsApproved = true,
                            LastName = "Singh",
                            Mobile = "8527500155",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NTPCJoining = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonalAreaId = 0,
                            ProjectCodeId = 0,
                            ProjectJoining = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuarterId = 0,
                            QuarterId2 = 0,
                            RegistratinDate = new DateTime(2021, 8, 4, 5, 48, 24, 166, DateTimeKind.Local).AddTicks(9172),
                            TypeId = 0
                        });
                });

            modelBuilder.Entity("dadri_api.Data.UserDept", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeptCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("DeptId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserDepts");
                });

            modelBuilder.Entity("dadri_api.Data.UserDeptGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("UserDeptGroups");
                });

            modelBuilder.Entity("dadri_api.Data.UserEmployer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("EmployerId");

                    b.ToTable("UserEmployers");

                    b.HasData(
                        new
                        {
                            EmployerId = 1,
                            EmployerName = "NTPC Ltd",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 2,
                            EmployerName = "CISF",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 3,
                            EmployerName = "UPL",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 4,
                            EmployerName = "BHEL",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 5,
                            EmployerName = "Gail",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 6,
                            EmployerName = "Power Grid",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 7,
                            EmployerName = "DPS",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 8,
                            EmployerName = "KV",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 9,
                            EmployerName = "DAV",
                            TypeId = 1
                        },
                        new
                        {
                            EmployerId = 10,
                            EmployerName = "Others",
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("dadri_api.Data.UserGrade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.ToTable("UserGrades");
                });

            modelBuilder.Entity("dadri_api.Data.UserLogin", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DeviceIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OtpGenerateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("dadri_api.Data.UserPersonalArea", b =>
                {
                    b.Property<int>("PersonalAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonalAreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalAreaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("PersonalAreaId");

                    b.ToTable("UserPersonalAreas");
                });

            modelBuilder.Entity("dadri_api.Data.UserProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("dadri_api.Data.UserRegister", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistratinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("RegisterId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("EmployerId");

                    b.HasIndex("Mobile")
                        .IsUnique()
                        .HasFilter("[Mobile] IS NOT NULL");

                    b.ToTable("UserRegisters");

                    b.HasData(
                        new
                        {
                            RegisterId = 1,
                            ApprovalDate = new DateTime(2021, 8, 4, 5, 48, 24, 165, DateTimeKind.Local).AddTicks(2771),
                            ApprovedBy = "009392",
                            Email = "narendrasingh@ntpc.co.in",
                            EmployerId = 1,
                            FirstName = "Narendra",
                            IsApproved = true,
                            LastName = "Singh",
                            Mobile = "8527500155",
                            ProjectId = 0,
                            RegistratinDate = new DateTime(2021, 8, 4, 5, 48, 24, 166, DateTimeKind.Local).AddTicks(5683)
                        });
                });

            modelBuilder.Entity("dadri_api.Data.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("URoleId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "URoleId");

                    b.HasIndex("UserId", "URoleId")
                        .IsUnique();

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("dadri_api.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("dadri_api.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dadri_api.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("dadri_api.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dadri_api.Data.Hotel", b =>
                {
                    b.HasOne("dadri_api.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("dadri_api.Data.UserDept", b =>
                {
                    b.HasOne("dadri_api.Data.UserDeptGroup", "UserDeptGroup")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDeptGroup");
                });

            modelBuilder.Entity("dadri_api.Data.UserLogin", b =>
                {
                    b.HasOne("dadri_api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dadri_api.Data.UserRegister", b =>
                {
                    b.HasOne("dadri_api.Data.UserEmployer", "UserEmployer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEmployer");
                });

            modelBuilder.Entity("dadri_api.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
